name: flutter_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+36

environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auth0_flutter: ^1.0.1
  flutter_dotenv: ^5.0.2
  google_fonts: ^3.0.1
  firebase_dynamic_links: ^5.0.6
  firebase_core: ^2.3.0
  url_launcher: ^6.1.7
  clipboard: ^0.1.3
  dio: ^4.0.6
  hooks_riverpod: ^2.1.1
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  build_runner: ^2.3.3
  json_serializable: ^6.5.4
  json_annotation: ^4.7.0
  flutter_hooks: ^0.18.5+1
  auto_route: ^5.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - images/logo.png