// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATF3mwitnJabx1KRmoF_iRuTaknhBsNfA',
    appId: '1:912789074192:web:abcf4f1367f065a34b3595',
    messagingSenderId: '912789074192',
    projectId: 'flutterapp-91f1c',
    authDomain: 'flutterapp-91f1c.firebaseapp.com',
    storageBucket: 'flutterapp-91f1c.appspot.com',
    measurementId: 'G-7MJQEXF1K2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2Ie7J7CgZiXcedpCtdPRZCZ2gvqFTWy8',
    appId: '1:912789074192:android:681eb859dfbbe0c94b3595',
    messagingSenderId: '912789074192',
    projectId: 'flutterapp-91f1c',
    storageBucket: 'flutterapp-91f1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDywOI-1qZXQFwmqD6proBjiVvLdf0CbN4',
    appId: '1:912789074192:ios:398681eb5d36f9d64b3595',
    messagingSenderId: '912789074192',
    projectId: 'flutterapp-91f1c',
    storageBucket: 'flutterapp-91f1c.appspot.com',
    iosClientId:
        '912789074192-igv9b6loahrrdim61npeig7a2psjir4k.apps.googleusercontent.com',
    iosBundleId: 'jp.co.rei.dev.1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDywOI-1qZXQFwmqD6proBjiVvLdf0CbN4',
    appId: '1:912789074192:ios:d7c5eef35baeb65d4b3595',
    messagingSenderId: '912789074192',
    projectId: 'flutterapp-91f1c',
    storageBucket: 'flutterapp-91f1c.appspot.com',
    iosClientId:
        '912789074192-751np0ljfiq5ga4qfc7tvptbtj2g4k0v.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth0',
  );
}
